"""add tools thinking vision size to stored model

Revision ID: c55280eb6f63
Revises: 4d925ff8f71e
Create Date: 2025-09-22 19:45:29.862944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'c55280eb6f63'
down_revision = '4d925ff8f71e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storedmodels', sa.Column('tools', sa.Boolean(), nullable=True))
    op.add_column('storedmodels', sa.Column('tools_description', sa.Text(), nullable=True))
    op.add_column('storedmodels', sa.Column('thinking', sa.Boolean(), nullable=True))
    op.add_column('storedmodels', sa.Column('vision', sa.Boolean(), nullable=True))
    op.add_column('storedmodels', sa.Column('size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storedmodels', 'size')
    op.drop_column('storedmodels', 'vision')
    op.drop_column('storedmodels', 'thinking')
    op.drop_column('storedmodels', 'tools_description')
    op.drop_column('storedmodels', 'tools')
    # ### end Alembic commands ###