"""add context window to StoredModels

Revision ID: 4d925ff8f71e
Revises: 77ac93e929b4
Create Date: 2025-09-22 19:14:45.780461

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '4d925ff8f71e'
down_revision = '77ac93e929b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storedmodels', sa.Column('context_window', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storedmodels', 'context_window')
    # ### end Alembic commands ###