"""added completition and capabilities list

Revision ID: 7cd519de4e94
Revises: fc08de4be930
Create Date: 2025-09-22 23:37:10.632106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '7cd519de4e94'
down_revision = 'fc08de4be930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storedmodels', sa.Column('completion', sa.Boolean(), nullable=True))
    op.add_column('storedmodels', sa.Column('capabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storedmodels', 'capabilities')
    op.drop_column('storedmodels', 'completion')
    # ### end Alembic commands ###