"""added model_name to conversation

Revision ID: 9e4f42a1589e
Revises: b3ce6a3c11b5
Create Date: 2025-10-03 09:48:08.208490

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '9e4f42a1589e'
down_revision = 'b3ce6a3c11b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'model_name')
    # ### end Alembic commands ###