"""added insert and embedding

Revision ID: a181283193de
Revises: 7cd519de4e94
Create Date: 2025-09-22 23:38:59.956255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'a181283193de'
down_revision = '7cd519de4e94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storedmodels', sa.Column('insert', sa.Boolean(), nullable=True))
    op.add_column('storedmodels', sa.Column('embedding', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storedmodels', 'embedding')
    op.drop_column('storedmodels', 'insert')
    # ### end Alembic commands ###